Added : ESLint, Prettier and Husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,6 +3,17 @@
 
 echo "Running pre-commit hook...🍺"
 
+npm run lint || (
+  echo "ESLint check failed. ❌ "
+  exit 1
+)
+echo "ESLint check completed successfully. ✅ "
+
+npm run prettier || (
+  echo "Prettier check failed. ❌ "
+  exit 1
+)
+
 echo "ESLint & Prettier check completed successfully. ✅ "
 
 npm run build || (
